Lesson3.tdd bdd
IgorSharov/thinknetica-ror-isharov pull request #1
Opened 2017-08-09 21:30 UTC by IgorSharov

- Редактор настроен
- Порядок и формат валидаторов и ассоциаций соблюдён
- Подключен рубокоп
- Использованы разные модели для Question и Answer
- Валидация на наличие вопроса в ответе реализована через question_id
- Валидация реализована через shoulda-matchers
- На внешний ключ добавлен индекс
- Добавлена зависимость на удаление связанных записей Answer при удалении Question

2017-08-10 07:33 UTC, vkurennov requested changes

2017-08-10 07:33 UTC, vkurennov commented on app/models/answer.rb
> +  validates :title, :body, :question_id, presence: true
Валидация на presence для question_id излишняя, т.к. в 5-х рельсах все ассоциации belongs_to валидируются автоматически

2017-08-10 07:33 UTC, vkurennov commented on app/models/answer.rb
> +  validates :question_id, numericality: true
Это тоже лишняя валидация, лучше добавить проверку на внешний ключ на уровне базы

2017-08-10 07:33 UTC, vkurennov commented on config/database.yml.sample
> +  adapter: sqlite3
Надеюсь, в реальности ты используешь postgres. Если нет, то лучше сразу на него перейти

2017-08-10 07:33 UTC, vkurennov commented on db/migrate/20170808210601_create_answers.rb
> +      t.belongs_to :question, index: true
В 5-х рельсах, опция `index: true` включена по-умолчанию, а чтобы добавить внешний ключ, достаточно добавить опцию `foreign_key: true`

2017-08-10 07:33 UTC, vkurennov commented on spec/models/question_spec.rb
> +  it { should have_many(:answers) }
Опцию dependent забыл протестировать

2017-08-10 14:48 UTC, IgorSharov commented on app/models/answer.rb
> +  validates :question_id, numericality: true
После удаления валидации question_id стали ругаться проверки в shoulda-matchers:
```
  should validate that :question_id cannot be empty/falsy (FAILED - 1)
  should validate that :question_id looks like a number (FAILED - 2)
```
Я правильно понял, что исходя из того, что "в 5-х рельсах все ассоциации belongs_to валидируются автоматически" можно просто убрать эти проверки, так как мы не проверяем чужой код?

И ещё вопрос:
код таблицы в postresql:
```
CREATE TABLE public.answers
(
  id bigint NOT NULL DEFAULT nextval('answers_id_seq'::regclass),
  question_id bigint,
  title character varying,
  body text,
  created_at timestamp without time zone NOT NULL,
  updated_at timestamp without time zone NOT NULL,
  CONSTRAINT answers_pkey PRIMARY KEY (id),
  CONSTRAINT fk_rails_3d5ed4418f FOREIGN KEY (question_id)
      REFERENCES public.questions (id) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
)
```
Поля не установились как "NOT NULL", а также сгенерировалось "ON DELETE NO ACTION".
Это нормально? Нужно ли мне в миграции дублировать логику из модели (  dependent: :destroy, presence: true и т.п.)?

2017-08-10 18:02 UTC, vkurennov commented on app/models/answer.rb
> +  validates :question_id, numericality: true
Ну так ты убери эти проверки из тестов, у тебя же нет валидации уже. 

> Я правильно понял, что исходя из того, что "в 5-х рельсах все ассоциации belongs_to валидируются автоматически" можно просто убрать эти проверки, так как мы не проверяем чужой код?

Да, верно.

> Это нормально? Нужно ли мне в миграции дублировать логику из модели ( dependent: :destroy, presence: true и т.п.)?

Это нормально, но такие опции в миграциях не продублируешь. Можно только not_null установить в true. В целом, в релсьах принято работать с базой только через модели, поэтому dependent и прочие валидации ставятся в них.

2017-08-11 10:07 UTC, vkurennov approved these changes

2017-08-11 10:07 UTC, vkurennov commented on app/models/answer.rb
> +  validates :title, :body, presence: true
А зачем ответу заголовок?

2017-08-15 07:10 UTC, merged