Lesson12.o auth
IgorSharov/thinknetica-ror-isharov pull request #10
Opened 2017-11-01 12:42 UTC by IgorSharov

### Реализовано:
1. Аутентификация через Vk и GitHub;
1. Реализован сценарий, когда провайдер не возвращает email.

2017-11-01 17:10 UTC, vkurennov requested changes

2017-11-01 17:10 UTC, vkurennov commented on app/models/user.rb
> +      user = new(email: email, password: password, password_confirmation: password)
Понятно, что мы в контексте класса User, но все же вызов new без указания класса явно, режет глаз.

2017-11-01 17:10 UTC, vkurennov commented on app/models/user.rb
> +    if (user = find_by(email: email))
Скобки у условий в руби не принято ставить

2017-11-01 17:10 UTC, vkurennov commented on app/models/user.rb
> +    auth_accounts.create(provider: auth.provider, uid: auth.uid)
Тут должен быть `create!`, ведь этот метод участвует в транзакции в 40-43 строках

2017-11-01 17:10 UTC, vkurennov commented on app/views/oauth/oauth_email.html.slim
> +  = hidden_field_tag 'provider', request.env['omniauth.auth'].provider
Плохое решение, т.к. ты светишь данные (их можно посмотреть в коде страницы). Лучше используй сессию - в ней данные зашифрованы.

2017-11-02 07:27 UTC, IgorSharov commented on app/models/user.rb
> +    if (user = find_by(email: email))
Rubocop заругался: [Use `==` if you meant to do a comparison or wrap the expression in parentheses to indicate you meant to assign in a condition](https://github.com/bbatsov/rubocop/pull/4605/files#diff-63d2f187b9fb380e1a062a0320b61d41)

2017-11-02 08:14 UTC, IgorSharov commented on app/views/oauth/oauth_email.html.slim
> +  = hidden_field_tag 'provider', request.env['omniauth.auth'].provider
Я наверное не очень понял то, о чём ты говорил на ИЗ. Идея была сделать так, чтобы пользователь мог открыть ссылку из почты на другой машине (например с телефона), а потом просто перелогинился с десктопа. Ведь, если хранить в сессии, то подтвердить можно будет только с того компа, с которого был введён адрес почты?

2017-11-02 12:06 UTC, vkurennov commented on app/models/user.rb
> +    if (user = find_by(email: email))
Аа, ну понял. Да, тогда ок, хотя все равно глаз режет :-)

2017-11-02 12:09 UTC, vkurennov commented on app/views/oauth/oauth_email.html.slim
> +  = hidden_field_tag 'provider', request.env['omniauth.auth'].provider
Верно, но ведь ссылка-то отсылается после заполнения этой формы. Т.е. заполнили форму - отправили письмо. Кликать по нему он может из другого браузера. Ни в скрытых полях, ни в сессии при этом значения не сохраняются.

Т.е. тебе после заполнения этой формы и перед отправкой письма нужно пришедшие uid и provaider сохранить в базе и связать с юзером. А когда он подвтердит аккаунт, то уже сможет входить с ними. 

А суть замечания в том, чтобы не светить эти данные, а держать скрытыми и зашифрованными в момент отображения и отправки формы.

2017-11-04 11:26 UTC, vkurennov approved these changes

2017-11-07 07:12 UTC, merged