Lesson5.acceptance testing
IgorSharov/thinknetica-ror-isharov pull request #3
Opened 2017-08-26 01:21 UTC by IgorSharov

__Реализованы следующие истории:__

- Пользователь может создавать вопрос;
- Пользователь может просматривать список вопросов;
- Пользователь, находясь на странице вопроса, может написать ответ на вопрос (т.е. форма нового ответа должна быть прямо на странице вопроса, без перехода на другую страницу);
- Пользователь может просматривать вопрос и ответы к нему.;
- Пользователь может войти в систему;
- Пользователь может выйти из системы;
- Пользователь может зарегистрироваться в системе;

- Только аутентифицированный пользователь может создавать вопросы и ответы;
- Автор может удалить свой вопрос или ответ, но не может удалить чужой вопрос/ответ/

2017-08-26 01:31 UTC, IgorSharov commented on spec/acceptance/answers_management_spec.rb
> +    sign_in user
Хотел написать вот так: `sign_in question.answers.first.user` без строк с 47 по 51.
В pry переменные user и question.answers.first.user видны и совпадают, но во вьюхе current_user = nil.
Почему так?

2017-08-26 09:16 UTC, vkurennov requested changes

2017-08-26 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
>    def new
У нас форма ответа должна быть на странице вопроса, поэтому экшн new не нужен

2017-08-26 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
>        render :new
Тут нужно рендерить страницу вопроса, ведь форма ответа должна быть именно там

2017-08-26 09:16 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user == current_user
* 1. Лучше проверять по user_id, чтобы не грузить ассоциацию из базы, она ведь не нужна.
* 2. Т.к. такая проверка будет встречаться часто, то лучше ее вынести в метод `User#author_of?`

2017-08-26 09:16 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user == current_user && @question.destroy
1. Замени сравнение на метод `User#author_of?`
2. Не нужно делать удаление в условии - это следствие условия, а не его часть.

2017-08-26 09:16 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <span class="author"><%= current_user == nil ? '' : current_user.email %></span>
Не нужно сравнивать с nil, т.к. nil и так воспринимается как false, поэтому достаточно написать:

`current_user ? '' : current_user.email`

Но можно применить оператор [safe navigation](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), тогда эта запись еще сильнее сократится: `current_user&.email`

2017-08-26 09:16 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <%= button_to 'Log in', new_user_session_path unless user_signed_in? or controller.controller_name == 'sessions' %>
Не используй or, and, not и т.д.  в условиях (да и вообще). У них самый низкий приоритет выполнения, это может вести к трудноуловимым багам в условиях. Возьми за правило всегда использовать только операторы &&, ||, ! и т.д.

2017-08-26 09:16 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +    <%= button_to 'Log out', destroy_user_session_path, method: :delete if user_signed_in?  %>
У тебя дважды проверка на `user_signed_in?` - тут и строкой выше. Лучше заменить на if/else

2017-08-26 09:16 UTC, vkurennov commented on app/views/questions/new.html.slim
>  h1 Ask your question:
Нужен вывод ошибок валидации

2017-08-26 09:16 UTC, vkurennov commented on app/views/questions/show.html.slim
> += button_to 'Delete question', question_path(@question), method: :delete if @question.user == current_user
Замени проверку на вызов `User#author_of?`

2017-08-26 09:16 UTC, vkurennov commented on app/views/questions/show.html.slim
> +    - if a.user == current_user
Замени проверку на вызов `User#author_of?`

2017-08-26 09:16 UTC, vkurennov commented on app/views/questions/show.html.slim
>  = button_to 'Add answer', new_question_answer_path(@question), method: :get
По условию задания, форма для ответа должна быть на странице вопроса

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +RSpec.feature 'User answers a question', '
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +RSpec.feature 'User removes his answer', '
Каждая спека должна быть в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    user = create(:user)
Сделай это через let и фабрики и сразу создай ответ, связанный с юзером:

```
let(:user) { ... }
let(:answer) { create(:answer, user: user) }
```

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    sign_in user
Этот вариант тоже не очень. Я выше написал как избавиться от строк 47-51.

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    expect(page).to have_css('.answer>a[data-method="delete"]')
Проверяй ссылки  по именам, а не по css, в acceptance-тестах нужно максимально проверять то, что **видит** пользователь. css он не видит.

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    expect(page).to have_current_path question_path(question)
Это не доказывает, что ответ был удален.

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    expect(page).to have_css('.answer>a[data-method="delete"]')
кстати, в этом случае наличие ссылки проверять не обязательно, т.к. ты вызываешь click_on, и это уже и проверит наличие ссылки неявно. Если ее не будет - тест упадет

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/answers_management_spec.rb
> +    expect(page).not_to have_css('.answer>a[data-method="delete"]')
Проверяй, что нет ссылки по ее названию

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/authentication_spec.rb
> +RSpec.feature 'User signs out', '
Каждая спека в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/authentication_spec.rb
> +RSpec.feature 'Unregistered user signs up', '
Каждая спека в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +    expect(page).to have_content 'Questions'
Надо проверить наличие заголовка и тела вопроса на странице

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +RSpec.feature 'User creates a question', '
Нужен тест на ошибки валидации - проверить, что система выводит их пользователю.

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +RSpec.feature 'User sees all questions', '
Каждая спека в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +RSpec.feature 'User sees the question with answers', '
Каждая спека в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +    expect(page.all('.answer').count).to eq question.answers.count
Лучше проверить сам текст овтетов, причем ответы желательно сделать разными (например, используя sequence  в фабриках для этого)

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +RSpec.feature 'User removes his question', '
Каждая спека в отдельном файле

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +    expect(page).to have_css('body>form.button_to>input[type="submit"][value="Delete question"]')
Это здесь лишнее

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +    expect(page).to have_current_path root_path
Это не доказывает, что вопрос был удален. Можно сделать редирект без удаления вопроса, тест пройдет

2017-08-26 09:16 UTC, vkurennov commented on spec/acceptance/questions_management_spec.rb
> +    expect(page).not_to have_css('body>form.button_to>input[type="submit"][value="Delete question"]')
Проверяй ссылки по имени, не нужно завязываться на верстку, она может измениться и придется менять тест, но ведь файтически, сценарий-то не поменяется

2017-08-26 09:16 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
> +    it 'removes user\'s answer' do
У тебя в контроллере условие, значит, надо проверять оба варианта - и когда условие выполнилось и когда не выполнилось

2017-08-26 09:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    it 'removes the question with its answer' do
Нужно проверить и вариант, когда не автор пытается удалить вопроса

2017-08-26 09:16 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +    let!(:question) { create(:question_with_answers, user: @user) }
Зачем создавать вопрос с ответами, если для теста нужен только вопрос?

2017-08-28 08:36 UTC, vkurennov requested changes

2017-08-28 08:36 UTC, vkurennov commented on Gemfile
> +gem 'sqlite3'
Ты какую базу используешь? postgres или sqlite3? Нужно использовать одну, при этом, postgres, тогда тебе не нужен будет этот гем

2017-08-28 08:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    redirect_to question_path(@question)
Нельзя делать редирект, если есть ошибки валидации. То, что ты их сохраняешь в флеш-сообщении - костыль. В любом случае, при редиректе потеряется все, что ввел пользователь и те не дашь ему возможности отредактировать свой ответ. Не делай так. При невалидном объекте нужно делать рендер, при валидном - редирект. И показывать ошибки в форме, а не через флеш-сообщения

2017-08-28 08:36 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    @answer.destroy if @answer.user.id? current_user.id
1. Очень неудачное название метода, назови лучше `owner?` или `author_of?`
2. Ты по прежнему грузишь ассоциацию user из базы, а этого делать не нужно, т.к. теряется всеь смысл проверки по id. Нужно вызывать этот метод у `current_user` и передавать ему `@answer` в качестве аргумента

2017-08-28 08:36 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +      redirect_to new_question_path
Нельяз делать редирект, если есть ошибки валидации

2017-08-28 08:36 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if @question.user.id? current_user.id
Вызывать метод нужно у `current_user`

2017-08-28 08:36 UTC, vkurennov commented on app/models/user.rb
> +  def id?(current_user_id)
1. Сюда нужно передавать объект, причем не current_user, а тот, у которого ты собираешься проверить авторство. А сам метод как раз и нужно вызывать у юзера (current_user).
2. Назови метод `author_of?` или `owner?`

2017-08-28 08:36 UTC, vkurennov commented on app/views/questions/new.html.slim
> +  - if flash[:validation_errors]&.any?
Выводи ошибки не через флеш, а через метод errors у самого объекта, для этого нужно делать рендер, а не редирект

2017-08-28 08:36 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if flash[:validation_errors]&.any?
Выводи ошибки не через флеш, а через метод errors у самого объекта, для этого нужно делать рендер, а не редирект

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect { click_on 'Add answer' }.not_to change(self, :current_path)
Не нужно проверять, что путь не изменился, это не так важно

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/answers/create_answer_spec.rb
> +    expect(page).to have_content 'Validation error'
Нужно конкретную ошибку валидации проверить

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/answers/remove_answer_spec.rb
> +    expect { click_on 'Delete answer' }.to change(question.answers, :count).by(-1)
В acceptance-тестах мы не можем проверять изменения в БД и т.д. мы можем проверять только то, что изменилось с т.з. пользователя. А изменилось то, что раньше текст ответа был, а когда он удалил его, то ответа на странице больше нет. Вот это и надо проверить.

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/answers/remove_answer_spec.rb
> +  scenario 'User tries to remove someone else\'s answer' do
Аналогичный тест нужен для незалогиненного юзера

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/questions/create_question_spec.rb
> +    expect(page).to have_content 'Validation error'
Нужно проверять конкретные сообщения об ошибках валидации

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/questions/remove_question_spec.rb
> +    expect { click_on 'Delete question' }.to change(Question, :count).by(-1).and \
Опять же проверяем только то, что может видеть пользователь. В базе он изменения видеть не может, только на странице

2017-08-28 08:36 UTC, vkurennov commented on spec/acceptance/questions/remove_question_spec.rb
> +  scenario 'User tries to remove someone else\'s question' do
Нужен аналогичный сценарий для незалогиненного юзера

2017-08-28 08:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          change(Answer, :count).by(-question.answers.count)
Не нужно проверять удаление ответов, мы это проверяем в тестах модели через тест ассоциации с опцией `dependent: :destroy`. Иначе получается, что ты начинаешь тестировать поведение этой опции, т.е. уже библиотеку ActiveRecord

2017-08-28 08:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +          change(Answer, :count).by(0)
Опять же не нужно проверять ответы

2017-08-28 08:36 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
> +        expect { delete :destroy, params: { id: question } }.to change(Question, :count).by(0).and \
Мы же не пишем "кол-во изменилось на 0", мы пишем "кол-во НЕ изменилось". Вот и в тестах пиши также (to_not change)

2017-08-28 08:36 UTC, vkurennov commented on spec/models/user_spec.rb
> +RSpec.describe User do
Где же тесты на твой метод `id?`?

2017-08-28 20:37 UTC, IgorSharov commented on app/views/questions/new.html.slim
>  h1 Ask your question:
Добавил

2017-08-28 20:39 UTC, IgorSharov commented on Gemfile
> +gem 'sqlite3'
Использую только postgres на убунту-виртуалке. Но иногда приходится работать на медленном компе под виндой без БД - тогда sqlite3, но это исключение.

2017-08-28 21:11 UTC, IgorSharov commented on spec/acceptance/answers/remove_answer_spec.rb
> +  scenario 'User tries to remove someone else\'s answer' do
Добавил

2017-08-29 08:08 UTC, vkurennov approved these changes

2017-08-29 08:08 UTC, vkurennov commented on Gemfile
> +gem 'sqlite3'
Тогда рекомендую вынести этот гем в группы development и test, чтобы потом при деплое он не мешал

2017-08-29 08:08 UTC, vkurennov commented on app/views/layouts/application.html.erb
> +        <% else %>
Не используй else с unless, тут и так условие инвертированное, да еще и с else, это усложняет понимание. Замени на if/else

2017-08-29 08:08 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  - if @answer.errors.any?
чтобы не дублировать в каждой форме, стоит вынести в общий универсальный паршл и использовать его

2017-08-29 19:34 UTC, IgorSharov commented on Gemfile
> +gem 'sqlite3'
Исправил

2017-08-29 19:35 UTC, IgorSharov commented on spec/models/user_spec.rb
> +RSpec.describe User do
Реализовал для #author_of?

2017-08-29 20:37 UTC, merged