Lesson7.ajax pt2
IgorSharov/thinknetica-ror-isharov pull request #5
Opened 2017-09-18 18:55 UTC by IgorSharov

**Реализованы следующие истории и задачи:**

- Только автор может отредактировать свой вопрос;
- Только автор может отредактировать свой ответ;
- Переделать удаление ответов на ajax;
- Автор вопроса может выбрать лучший ответ для своего вопроса (лучший ответ может быть только 1);
- Автор вопроса может выбрать другой ответ как лучший, если у вопроса уже выбран лучший ответ;
- Если у вопроса выбран лучший ответ, то он отображается первым в списке ответов.

2017-09-18 22:41 UTC, vkurennov requested changes

2017-09-18 22:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    params.require(:bool)
Эта строка не имеет смысла, т.к. никак далее не влияет на параметры.

2017-09-18 22:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    old_best_answer = @question.answers.find_by(best_answer: true)
Слишком много логики в контроллере, сделай метод в модели, а здесь просто вызывай его

2017-09-18 22:41 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +      old_best_answer.save
Используй update, чтобы и обновить атрибут и сразу сохранить его в базе

2017-09-19 16:01 UTC, vkurennov requested changes

2017-09-19 16:01 UTC, vkurennov commented on app/models/question.rb
> +    answers.find(id).update(best_answer: true)
Лучше передвать объект, иначе получается непонятно. Ну и надо же еще снять флаг лучшего ответа у старого лучшего, если он есть. Это надо сделать тут же, а не в контроллере. И применить транзакцию, чтобы изменения были атомарными. Иначе, мы можем несколько ответов назначить лучшими

2017-09-19 16:01 UTC, vkurennov commented on app/models/question.rb
> +  def best_answer
Где тесты моделей на эти методы?

2017-09-21 14:28 UTC, vkurennov requested changes

2017-09-21 14:28 UTC, vkurennov commented on app/models/question.rb
> +    params_hash[:new_best_answer].update(best_answer: true) if params_hash[:set_new] == 'true'
А у  тебя в хеше сразу объект или его id приходит?

2017-09-21 14:28 UTC, vkurennov commented on app/models/question.rb
> +    params_hash[:new_best_answer].update(best_answer: true) if params_hash[:set_new] == 'true'
И т.к. 2 апдейта, то тут нужна [транзакция](http://api.rubyonrails.org/classes/ActiveRecord/Transactions/ClassMethods.html), чтобы изменения были атомарными. Только помни, что транзакция откатывается только в случае исключения.

2017-09-23 09:57 UTC, IgorSharov commented on app/models/question.rb
> +    params_hash[:new_best_answer].update(best_answer: true) if params_hash[:set_new] == 'true'
В хэше -- объект, да.
Транзакцию сделал с бэнг методами, спасибо!

2017-09-24 11:07 UTC, vkurennov approved these changes

2017-09-25 08:43 UTC, merged