Lesson9.ajax pt3
IgorSharov/thinknetica-ror-isharov pull request #7
Opened 2017-10-08 12:43 UTC by IgorSharov

**Реализованы следующие истории, используя JSON:**

- Аутентифицированный пользователь может голосовать за понравившийся вопрос/ответ
- Пользователь не может голосовать за свой вопрос/ответ
- Пользователь может проголосовать "за" или "против" конкретного вопроса/ответа только один раз (нельзя голосовать 2 раза подряд "за" или "против")
- Пользователь может отменить свое решение и после этого переголосовать.
- У вопроса/ответа должен выводиться результирующий рейтинг (разница между голосами "за" и "против")

2017-10-08 16:01 UTC, vkurennov requested changes

2017-10-08 16:01 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +  def create
У тебя слишком много логики в контроллере. Отдели логику создания голоса и возвращаемого результата, и логику создания голоса вынеси в модели (в консерн моделей)

2017-10-08 16:01 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.new do |v|
Все это можно сделать гораздо более красиво: контроллер Votes вложить в вопросы и ответы, динамически определять родителя и через его ассоциации создавать новый голос.

2017-10-08 16:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +module Votable
Вот сюда же стоит вынести всю логику создания голоса

2017-10-08 16:01 UTC, vkurennov commented on app/models/concerns/votable.rb
> +  def rating_by_user(user_id)
Этот и следующий метод более логично держать в классе User

2017-10-08 16:01 UTC, vkurennov commented on app/models/vote.rb
> +  enum vote_type: %i[up down]
enum даст значения 0 и 1, и у тебя будет неправильно считаться рейтинг, т.к. по факту будут учитывться только голоса "за". Хотя ты это делаешь через мультипликатор в контроллере, но гораздо проще сразу хранить 1 или -1 в базе.

2017-10-08 16:01 UTC, vkurennov commented on app/views/shared/_rating.html.slim
> +    = link_to '+', vote_path(object.class, object.id, 1, vote_type: :up), method: :post, remote: true, data: { type: :json }, class: [:up, rating_by_user == 0 ? nil : rating_by_user > 0 ? 'chosen_lin
Передавать тип и id родителя в параметрах не очень красиво, лучше использовать вложенные ресурсы для этого

2017-10-08 16:01 UTC, vkurennov commented on config/routes.rb
> +  post '/votes/:votable_type/:votable_id/:value', to: 'votes#create', as: :vote
Ну это совсем уж костыль. Вспоминай про вложенные ресурсы и кастомные экшены.

2017-10-08 17:59 UTC, IgorSharov commented on app/models/vote.rb
> +  enum vote_type: %i[up down]
Рейтинг я считаю по полю :value, в котором хранится реальное значение конкретного голоса (сейчас это могут быть только 1 или -1, с возможностью в будущем задавать вес голоса для пользователя).
:value_type имеют enum (:up и :down) для контроля чётного голосования отдельного пользователя: то есть у меня нет кнопки reset - если пользователь проголосовал "+", то он сначала должен нажать на "+" второй раз, чтобы отменить свой голос. На уровне БД на второй клик по "+" создастся запись с vote_type: :up, но с value: -1. Так сделано, чтобы не путать между собой "поправочные" голоса с -1 и обычные отрицательные голоса. То же самое для "-"

2017-10-08 18:18 UTC, IgorSharov commented on app/controllers/votes_controller.rb
> +  def create
Я правильно понимаю, что в случае если в процессе создания голоса (в консерне моделей) на каком либо этапе возникнут ошибки (например у меня: 'Self voting denied' или 'Incorrect vote type' ) мне надо будет руками записать их в @vote.errors, а на уровне контролера смотреть есть ли ошибки в этом хэше?

2017-10-08 18:33 UTC, IgorSharov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.new do |v|
Не понял рекомендацию. Нужно создать консерн Voted который добавит кастомные экшены в вопросы и ответы? То есть отдельного контроллера VotesController быть не должно?

2017-10-08 18:34 UTC, IgorSharov commented on config/routes.rb
> +  post '/votes/:votable_type/:votable_id/:value', to: 'votes#create', as: :vote
Идея была такая: унифицировать набор параметров запроса, чтобы независимо от родительского типа создавать голос, а потом по связям "снизу-вверх" получать родительскую запись. То есть во вьюхе  я мог использовать единственный хелпер vote_path, чтобы генерить нужную ссылку.
Как я понял твои рекомендации - правильнее идти "сверху-вниз", то есть из родительского объекта билдить голос. Я сделал роуты через консерны - вложил votes в маршруты вопросов и ответов. Получается теперь у меня 2 хелпера: question_answer_votes_path и question_votes. Выходит, что универсальный паршл _ranking, который можно будет использовать и для вопросов, и для ответов должен учитывать типа объекта (будет разный набор параметров). Это не сложнее?

2017-10-08 18:41 UTC, IgorSharov commented on spec/models/user_spec.rb
> +  describe 'rating methods' do
Как правильно писать спеку, чтобы проверять все Votable, а не только Question?

2017-10-09 07:45 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +  def create
Тут можно по-разному сделать, зависит от того, где именно будет валидация происходить. Если в модели Vote, то ты просто через кастомные валидации это можешь сделать, если через консерны в других моделях, то так делать нельзя, можно просто вернуть некоторый код и сообщение об ошибке.

2017-10-09 07:47 UTC, vkurennov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.new do |v|
Нет, контроллер оставь. Сделай ресурс votes, вложи его в вопросы и ответы на уровне роутинга. И можно динамически определить, какой ресурс родительский, например так: https://stackoverflow.com/questions/26318815/polymorphic-controller-and-calling-object

2017-10-09 07:48 UTC, vkurennov commented on app/models/vote.rb
> +  enum vote_type: %i[up down]
А зачем так сложно? Все можно упростить и не писать никаких типов, достаточно значения.

2017-10-09 07:48 UTC, vkurennov commented on config/routes.rb
> +  post '/votes/:votable_type/:votable_id/:value', to: 'votes#create', as: :vote
Ну вот это и делается через вложенные ресурсы и консерн на уровне роутинга.

2017-10-09 22:09 UTC, IgorSharov commented on app/models/concerns/votable.rb
> +module Votable
Вынес логику создания, но мне не нравится, что передаётся объект current_user и как возвращаются ошибки. Как красивее сделать?

2017-10-09 22:15 UTC, IgorSharov commented on app/models/vote.rb
> +  enum vote_type: %i[up down]
"-" во вьюхе блокируется классом, который можно снять и отправить голос "-" без сброса "+". Это собьёт счётчик на основании которого считаются классы при рендере. Короче, получается, что если  не знать тип голоса, то будет невозможно понять -1 это голос "минус" или сброс счётчика "плюс".

2017-10-09 22:16 UTC, IgorSharov commented on spec/models/user_spec.rb
> +  describe 'rating methods' do
пока задублирую. позже вынесем их в шаред-спеку.

2017-10-09 22:18 UTC, IgorSharov commented on app/controllers/votes_controller.rb
> +  def create
Сделал через консерны, про возврат ошибки вопрос далее.

2017-10-09 22:19 UTC, IgorSharov commented on app/controllers/votes_controller.rb
> +    @vote = Vote.new do |v|
сделал, спасибо! пришлось зарефакторить ответы на shallow routes

2017-10-09 22:19 UTC, IgorSharov commented on app/models/concerns/votable.rb
> +  def rating_by_user(user_id)
Есть.

2017-10-09 22:20 UTC, IgorSharov commented on app/views/shared/_rating.html.slim
> +    = link_to '+', vote_path(object.class, object.id, 1, vote_type: :up), method: :post, remote: true, data: { type: :json }, class: [:up, rating_by_user == 0 ? nil : rating_by_user > 0 ? 'chosen_lin
Сделано.

2017-10-09 22:20 UTC, IgorSharov commented on config/routes.rb
> +  post '/votes/:votable_type/:votable_id/:value', to: 'votes#create', as: :vote
Исправлено.

2017-10-11 09:40 UTC, vkurennov approved these changes

2017-10-11 09:40 UTC, vkurennov commented on app/models/concerns/votable.rb
> +module Votable
Ну с current_user все ок, тут по-другому не сделат. Насчет ошибок - их лучше бы сделать как кастомные валидации в самом Vote.

2017-10-11 09:40 UTC, vkurennov commented on app/models/concerns/votable.rb
> +      vote.errors.add(:vote_type, 'Incorrect vote type') if previous_vote_by_user.vote_type != vote.vote_type
Вообще, это плохая практика, когда один объект добавляет ошибки валидации в другой объект. Объект должен сам валидировать свои данные. Лучше всего перенести проверки в кастомные валидации в модель Vote

2017-10-11 09:46 UTC, merged