Lesson10.action cable
IgorSharov/thinknetica-ror-isharov pull request #8
Opened 2017-10-16 16:19 UTC by IgorSharov

**С применением ActionCable реализовано:**

- При добавлении ответа к вопросу, этот ответ появляется у всех пользователей, у которых открыт этот вопрос;
- При добавлении нового вопроса, у всех пользователей, у которых открыт список вопросов, появляется новый вопрос в списке;
- Пользователь может добавлять комментарии к вопросам/ответам;
- При добавлении комментария, он появляется у всех пользователей, у которых открыта страница с тем же вопросом.

2017-10-17 09:02 UTC, vkurennov requested changes

2017-10-17 09:02 UTC, vkurennov commented on app/assets/javascripts/cable.js
> +function killAllChannelsExcept(subscription) {
Вообще, вручную не нужно закрывать подписку. Если переходим на страницу, где подписки нет, AC ее закроет автоамтом через несколько секунд, там же пинг постоянный идет.

2017-10-17 09:02 UTC, vkurennov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +        jsonData = JSON.parse(data)
Если не ошибаюсь, данные уже распарсенные приходят.

2017-10-17 09:02 UTC, vkurennov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +    subscription = App.cable.subscriptions.create { channel: 'QuestionChannel', question_id: gon.question_id },
Не очень удачное название канала. Тут у тебя обрабатываются комментарии, а канал называется QuestionChannel. То, что там параметр стоит - это верно, но вот имя канала вводит в заблуждение

2017-10-17 09:02 UTC, vkurennov commented on app/channels/question_channel.rb
> +class QuestionChannel < ApplicationCable::Channel
Сделай отдельный канал для комментариев и ответов. Не нужно все слать в один канал, это усложняет код и его поимание.

2017-10-17 10:19 UTC, IgorSharov commented on app/assets/javascripts/cable.js
> +function killAllChannelsExcept(subscription) {
Такого не происходит. Я подозреваю, что из-за turbolinks. То есть, если я зайду на страницу ответа, потом на индекс вопросов и обратно на страницу ответов yf djghjc, то в js App.cable.subscribes.subscribes будет 3 подписки. То есть при добавлении другим пользователем ответа на данный вопрос у меня он добавится дважды. При это ещё и будут приходить новые вопросы, которые на данной странице к отображению не требуются.

2017-10-17 10:20 UTC, IgorSharov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +        jsonData = JSON.parse(data)
Вообще, строка приходит. Может в контроллере что-то не так?

2017-10-17 10:30 UTC, IgorSharov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +    subscription = App.cable.subscriptions.create { channel: 'QuestionChannel', question_id: gon.question_id },
Идея была, что тут обрабатывается канал конкретного вопроса. А в нём - уже ответы и комментарии.

2017-10-17 10:31 UTC, IgorSharov commented on app/channels/question_channel.rb
> +class QuestionChannel < ApplicationCable::Channel
Ясно. То есть хорошая практики канал называть по множественному числу имени объяктов, которые пересылаются по данному каналу?

2017-10-17 10:38 UTC, vkurennov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +    subscription = App.cable.subscriptions.create { channel: 'QuestionChannel', question_id: gon.question_id },
Да, я понял идею, но в целом такой подход запутывает.

2017-10-17 10:39 UTC, vkurennov commented on app/channels/question_channel.rb
> +class QuestionChannel < ApplicationCable::Channel
Ну тут нет именно такой практики, просто нужно называть каналы исходя из того, с чем они работают.

2017-10-17 10:40 UTC, vkurennov commented on app/assets/javascripts/channels/subscriptions/question.coffee
> +        jsonData = JSON.parse(data)
Попробуй в контроллерах вместо to_json использовать as_json.

2017-10-17 10:40 UTC, vkurennov commented on app/assets/javascripts/cable.js
> +function killAllChannelsExcept(subscription) {
Да, проблема понятна. подумаю, как можно ее обойти, если найду более красивое решение - напишу

2017-10-18 10:41 UTC, vkurennov approved these changes

2017-10-18 10:46 UTC, merged